name: XpBank
version: 1.0.1
main: org.ctp.xpbank.XpBank
api-version: 1.13
commands:
  xpopen:
    aliases: [xpbankopen,xpbopen,openbank]
    description: Opens the Xp Bank.
  xpadmin:
    description: Add or remove experience from banks.
permissions:
  xpbank.free:
    description: Allows players to open the bank for free
    default: op
  xpbank.admin:
    description: Allows players to access the admin command
    default: op